#!/usr/bin/env node
/**
 * Software Bill of Materials for the *runtime* bundle.
 *
 *   node scripts/sbom.mjs [outDir=sbom]
 *
 * Writes:
 *   localcompress.cdx.json   CycloneDX 1.5 (via `npm sbom`, production deps only)
 *   LICENSES.md              license inventory with WASM binaries listed separately
 *   wasm-binaries.json       SHA-256 of every WASM file shipped, for verification
 */
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = join(import.meta.dirname, '..');
const out = process.argv[2] ?? join(root, 'sbom');
mkdirSync(out, { recursive: true });

const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm';
const cdx = execFileSync(npm, ['sbom', '--sbom-format', 'cyclonedx', '--omit', 'dev', '--sbom-type', 'application'], { cwd: root, maxBuffer: 64 * 1024 * 1024 }).toString();
writeFileSync(join(out, 'localcompress.cdx.json'), cdx);

// Collect production dependency tree from the lockfile.
const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8'));
const prod = Object.entries(lock.packages)
  .filter(([path, p]) => path.startsWith('node_modules/') && !p.dev && !p.link)
  .map(([path, p]) => {
    const name = path.replace(/^.*node_modules\//, '');
    const pj = existsSync(join(root, path, 'package.json')) ? JSON.parse(readFileSync(join(root, path, 'package.json'), 'utf8')) : {};
    return { name, version: p.version, license: p.license ?? pj.license ?? 'UNKNOWN', resolved: p.resolved, integrity: p.integrity, repository: typeof pj.repository === 'string' ? pj.repository : pj.repository?.url };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

// WASM binaries shipped in the bundle (the highest-risk artefacts).
const wasm = [];
const walk = (d) => readdirSync(d).flatMap((f) => (statSync(join(d, f)).isDirectory() ? walk(join(d, f)) : [join(d, f)]));
for (const p of prod) {
  const dir = join(root, 'node_modules', p.name);
  if (!existsSync(dir)) continue;
  for (const f of walk(dir).filter((f) => f.endsWith('.wasm'))) {
    wasm.push({ package: `${p.name}@${p.version}`, file: relative(root, f), bytes: statSync(f).size, sha256: createHash('sha256').update(readFileSync(f)).digest('hex') });
  }
}
writeFileSync(join(out, 'wasm-binaries.json'), JSON.stringify(wasm, null, 2));

const copyleft = prod.filter((p) => /GPL|AGPL|LGPL|MPL|EPL|CDDL/i.test(p.license));
const md = `# LocalCompress — runtime dependency & license inventory

Generated by \`scripts/sbom.mjs\` from \`package-lock.json\`. Production (shipped) dependencies only.
Every package is pinned to an exact version and verified by its lockfile integrity hash.

| Package | Version | License | Integrity |
|---|---|---|---|
${prod.map((p) => `| ${p.name} | ${p.version} | ${p.license} | \`${(p.integrity ?? '').slice(0, 22)}…\` |`).join('\n')}

## Licenses requiring review

${copyleft.length ? copyleft.map((p) => `- **${p.name}** — ${p.license}${p.license.includes('MPL') ? ' (file-level copyleft: modifications to its own files must be published; using it unmodified in a bundle is permitted)' : ''}`).join('\n') : 'None.'}

## WebAssembly binaries

| Package | File | Bytes | SHA-256 |
|---|---|---|---|
${wasm.map((w) => `| ${w.package} | \`${w.file.replace(/^node_modules\//, '')}\` | ${w.bytes} | \`${w.sha256}\` |`).join('\n')}

These binaries are prebuilt by their upstream projects (Squoosh / jSquash). See
docs/MAINTENANCE.md § "Rebuilding WASM from source" for reproducing them.

## Fonts (bundled, OFL-1.1)

Geist, Geist Mono (Vercel), Instrument Serif — via @fontsource packages listed above.
`;
writeFileSync(join(out, 'LICENSES.md'), md);
console.log(`✓ SBOM: ${prod.length} runtime packages, ${wasm.length} WASM binaries → ${relative(root, out) || '.'}`);
